### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by zeldalegends** [N5GEH/n5geh.tools.entirety#106]
Hi,

After successfully installed, is there any example or tutorial for its usage? Some sort of hello world guide - if not a complete documentation - to use the GUI and get starting?

Thanks

**Comment by SBlechmann** [comment]
Hey @zeldalegends,
thank you for the interest in using entirety! We are currently working on providing a basic overview about the different apps. Once it's pushed we invite you to test it :)

**Comment by iripiri** [comment]
Hello,
I'm checking the documentation and noticed that the PostgreSQL development package is a dependency but not documented. An error occurs when trying to install the requirements.txt and in my case (Ubuntu OS) could be solved with `sudo apt-get install libpq-dev`

Maybe the docs can be structured in the following?

- Introduction
- Getting started
  - Prerequisites
  - Explanation of .env file
  - How to run
- Login
- ...

**Comment by djs0109** [comment]
Good point @iripiri . We are considering to rewrite the readme of Entirety. I can imagine the structure to be like:
- Introduction
- Getting started
  - Prerequisites
  - Explanation of .env file
  - How to deploy (Entirety Step by Step)
  - How to use (GUI Tutorials)
  - How to develop (Development doc)

And maybe we only need to reference the docs in our main readme
