### ISSUE TITLE
Seperate Env for DB-Password and User in Django

### ISSUE THREAD

**Issue by StWiemann** [N5GEH/n5geh.tools.entirety#112]
The DB-URL should be generated within the Django container using the necessary envs (DB-URL, DB-USER, DB-PWD) to be in line with other docker services. This way the whole URL would have to be a secret when using it with e.g. Kubernetes, leading to multiple secrets with essentially the same information. Furthermore, it would improve the user experience.

**Comment by djs0109** [comment]
That's a good point. @StWiemann will this file reflect what you mean? https://github.com/N5GEH/n5geh.tutorials.entirety_step_by_step/blob/main/docker/docker-compose.yml

**Comment by StWiemann** [comment]
@djs0109 It does indeed reflect what I mean. But it only shows what I would suggest to avoid. Entirety resp. Django takes only the environmental "DATABASE_URL", which contains not only the URL, but the user has to specify protocol (not that bad, but should be made obvious), DB username and DB password in just one environmental.
For a somewhat more easy approach, I would suggest splitting that into "DATABASE_URL", "DATABASE_USER" and "DATABASE_PWD". It would enable the user to set project-wide secrets which could be reused and avoid maintaining more than one user/password-entry. Additionally, the user would not have to know how to authenticate against Postgres through the URL.

**Comment by djs0109** [comment]
You are right! This point was previously discussed but unfortunately left behind. In our local `.env`, I found the following unused environment variables.
```
DATABASE_PORT=5432
DATABASE_USER=postgres
DATABASE_PASSWORD=postgrespw
DATABASE_HOST=localhost
```
Would these namings make sense to you? Like to separate the `DATABASE_URL` to `DATABASE_HOST` and `DATABASE_PORT`

**Comment by StWiemann** [comment]
Good call to even split the port. Looks good!
