### ISSUE TITLE
Invalid Request Block Size

### ISSUE THREAD

**Issue by StWiemann** [N5GEH/n5geh.tools.entirety#122]
Following the Tutorial on this I set up Entirety but ran into "invalid request block size: 21327 (max 4096)...skip".

This is due to starting the DJango-Server only with the "socket"-argument.

Changing the runner.sh like this solved it:

```uwsgi --http-socket "0.0.0.0:8000" --module entirety.wsgi --master --processes 4 --threads 2```

**Comment by Nils98Ar** [comment]
We have the same problem!

**Comment by sbanoeon** [comment]
Can you please describe your workflow? Are you using NGINX in front of uwsgi?

**Comment by Nils98Ar** [comment]
Yes, we have an nginx ingress controller in front. 

The fix proposed by @StWiemann works for us. Currently we are building the image ourselves.

**Comment by djs0109** [comment]
In [django documentation](https://docs.djangoproject.com/en/4.2/howto/deployment/wsgi/uwsgi/) it states that:

"_uWSGI operates on a client-server model. Your web server (e.g., nginx, Apache) communicates with a django-uwsgi “worker” process to serve dynamic content._"

And in this case, `--socket` should be used.
@Nils98Ar Could you share the relevant part in your nginx config file? i.e., how you forward client requests to entirety?

**Comment by Nils98Ar** [comment]
Ah okay I think we are maybe missing a webserver between the nginx ingress controller (http/s reverse proxy only) and entirety that speaks the uwsgi protocol to the workers (e.g. nginx with `uwsgi_pass` directive).

It seems to work with `--http-socket` because this enables the embedded http/s webserver in front of the workers.

The question is if we want to use it in production:
> **Can I use uWSGI’s HTTP capabilities in production?**
> If you need a load balancer/proxy it can be a very good idea. It will automatically find new uWSGI instances and can load balance in various ways. If you want to use it as a real webserver you should take into account that serving static files in uWSGI instances is possible, but not as good as using a dedicated full-featured web server. If you host static assets in the cloud or on a CDN, using uWSGI’s HTTP capabilities you can definitely avoid configuring a full webserver.

(https://uwsgi-docs.readthedocs.io/en/latest/HTTP.html)

**Comment by djs0109** [comment]
Exactly, if we change to `--http-socket`, we are not actually using nginx as the HTTP server, and we will get following error if we trying to do so:
> upstream prematurely closed connection while reading response header from upstream, client: 192.168.48.1, server: localhost, request: "GET / HTTP/1.1", upstream: "uwsgi://192.168.48.3:8000", host: "localhost"

The image that we provided is designed for using nginx as the HTTP server, just as described in the [step by step](https://github.com/N5GEH/n5geh.tutorials.entirety_step_by_step). Basically, we do similar thing as this [tutorial ](https://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html?highlight=unix%20socket)
