### ISSUE TITLE
token for semantic release outdated

### ISSUE THREAD

**Issue by djs0109** [N5GEH/n5geh.tools.entirety#133]
Semantic release can not push commit into `main`. 
```
[remote rejected] main -> main (protected branch hook declined)
```

**Comment by djs0109** [comment]
@sbanoeon  It seems that the github actions can not push commit into protected branches. See [here](https://github.com/orgs/community/discussions/25305)

**Comment by djs0109** [comment]
[This](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions) seems to be the official solution to this problem

**Comment by sbanoeon** [comment]
Creating a GitHub App to generate an installation access token looks better than using personal access token for workflow.

**Comment by djs0109** [comment]
This issue is solved https://github.com/N5GEH/n5geh.tools.entirety/pull/135
