### ISSUE TITLE
Mark project URL and logo as non-mandatory

### ISSUE THREAD

**Issue by SBlechmann** [N5GEH/n5geh.tools.entirety#139]
In the projects app, mark project URL and project logo as non-mandatory.

**Comment by djs0109** [comment]
Is it relevant with this https://github.com/N5GEH/n5geh.tools.entirety/issues/84?

**Comment by SBlechmann** [comment]
Ah, then I deployed an older version when I tested it. 

Let me verify and then close this issue if it's not necessary anymore.
