### ISSUE TITLE
Renaming Attributes Creates a New Attribute

### ISSUE THREAD

**Issue by SzalonyNiemiec** [N5GEH/n5geh.tools.entirety#150]
When editing the name of an attribute and saving, instead of changing the existing attribute this creates a new attribute.
Steps to reproduce:
1)Create an entity with an attribute "Name"
2)Edit the entity, and change the name of the attribute to "name" and save tha change

<img width="1062" alt="Screenshot 2024-01-10 213940" src="https://github.com/N5GEH/n5geh.tools.entirety/assets/46593845/d0479a84-7caa-4cdd-9ace-d630aa0b8464">
<img width="1098" alt="Screenshot 2024-01-10 214054" src="https://github.com/N5GEH/n5geh.tools.entirety/assets/46593845/85fb542b-cf6e-4d00-868a-89a78857bc52">
<img width="1094" alt="Screenshot 2024-01-10 214142" src="https://github.com/N5GEH/n5geh.tools.entirety/assets/46593845/3ba42e78-1a32-4a12-bbee-6a4a49a1fba4">

**Comment by djs0109** [comment]
Fixed in current development
