### ISSUE TITLE
Redirect of Project Overview Save Button

### ISSUE THREAD

**Issue by SBlechmann** [N5GEH/n5geh.tools.entirety#195]
Currently, when hitting the save button in the project edit page, the user is redirected to the project overview page.

Imo, the user should stay within the edit page for that project.

**Comment by djs0109** [comment]
Do you mean the project landing page for that project right? Like that
![grafik](https://github.com/user-attachments/assets/50607bc0-1e3d-4da3-bbda-50f54582939d)
If yes, I agree with that.

**Comment by SBlechmann** [comment]
That would already be enough, imo. Initially, I meant to stay within the edit process but I believe this would suffice.
