### ISSUE TITLE
Empty float value in Attribute value leads to error

### ISSUE THREAD

**Issue by sbanoeon** [N5GEH/n5geh.tools.entirety#206]
When creating an entity with an attribute of type Float and empty value, the entity is successfully created but upon list all entities, it leads to error that it can not convert "" into type Float.

**Comment by djs0109** [comment]
This error is fixed in filip 0.5.0. I think if we use filip 0.5.0 in #152 , then this issue should also be fixed

**Comment by djs0109** [comment]
fixed by #152
