### ISSUE TITLE
User experience improvement

### ISSUE THREAD

**Issue by djs0109** [N5GEH/n5geh.tools.entirety#84]
After an internal test run, we have received some feedback regarding the user experience:

- [x] Entirety Logo and the name "Entirety" should be displayed somewhere on the top bar
- [x] Some fields of project should be optional
  - [x] Logo
  - [x] Homepage URL
- [x] In Subscriptions App, give the `entity id` under `subject` as a drop-down list, which shows the currently available entity IDs as suggestions
- [x] In Subscription App, the save button should be moved to the button just as in Entity and Device App

**Comment by richardmarston** [comment]
hi @djs0109

**Comment by djs0109** [comment]
I forgot that we have changed the workflow now we should create a new branch via github

**Comment by richardmarston** [comment]
Notes (I will edit this multiple times, please ignore for now)
When the logo is left black, the n5geh logo is used:
![n5geh](https://user-images.githubusercontent.com/994657/200554833-4fe97545-6a8d-402c-be14-a726fa5a089f.png)

**Comment by richardmarston** [comment]
hi @sbanoeon @djs0109

https://github.com/N5GEH/n5geh.tools.entirety/commit/c25d0289d32e9247751c3d95268d90c9b9764beb#commitcomment-89992171

**Comment by sbanoeon** [comment]
Hi @richardmarston , please see the corresponding comment on the commit :) And open a PR for the changes in this branch, thanks :)
